version: '3'

services:
  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - agent_network
    deploy:
      mode: global

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    #ports:
    #  - mode: host
    #    published: 9000
    #    target: 9000
    volumes:
      - portainer_data:/data
    deploy: 
      labels:
        - "traefik.frontend.rule=Host:portainer.${MYDOMAIN}"
        - "traefik.port=9000"
    networks:
      - service
      - agent_network
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  service:
    external:
      name: swarm-service
  agent_network:
    driver: overlay

volumes:
  portainer_data:
    driver: nfs
    driver_opts:
      share: 172.17.0.1/srv/data/volumes/portainer_data
